## Assignment 2: Transition Matrix and Data Generation

### Author: Shuang (Sophie) Hu

#### 1. Clean your input text by removing all punctuation, except periods. Convert everything to lower case.

In [1]:
# Download and open the input text file
data_file_location = "input.txt"
inputfile = open(data_file_location, 'r', encoding='utf8')

# Print the first 5 lines to check
for x in range(5):
  print(inputfile.readline())

i lived there two years and two months.

at present i am a sojourner in civilized life again.

i should not obtrude my affairs so much on the notice of my readers if very particular inquiries had not been made by my townsmen concerning my mode of life which some would call impertinent though they do not appear to me at all impertinent but considering the circumstances very natural and pertinent.

some have asked what i got to eat if i did not feel lonesome if i was not afraid and the like.

others have been curious to learn what portion of my income i devoted to charitable purposes and some who have large families how many poor children i maintained.



#### 2. For each sentence, create pairs of consecutive words (suggestion: change the '.' to the word 'PERIOD')
For example："I lived there two years and two months. At present I am a sojourner in civilized life again."

**Hint1**: Given two lists, you can use the `zip` function to combine them. **Hint2**: You can create a list which includes all elements, except the first one, by using slicing: mylist[1:]

In [3]:
# Change the "." to the word "PERIOD"
data_file_location = "input.txt"
inputfile = open(data_file_location, 'r', encoding='utf8')

lines = inputfile.readlines()
for i in range(len(lines)):
    lines[i] = lines[i].replace("."," PERIOD")

# Print the first 5 lines to check
print(lines[0:5])

['i lived there two years and two months PERIOD\n', 'at present i am a sojourner in civilized life again PERIOD\n', 'i should not obtrude my affairs so much on the notice of my readers if very particular inquiries had not been made by my townsmen concerning my mode of life which some would call impertinent though they do not appear to me at all impertinent but considering the circumstances very natural and pertinent PERIOD\n', 'some have asked what i got to eat if i did not feel lonesome if i was not afraid and the like PERIOD\n', 'others have been curious to learn what portion of my income i devoted to charitable purposes and some who have large families how many poor children i maintained PERIOD\n']


In [5]:
# Create a list which includes all elements
words = []
for i in range(len(lines)):
        words += lines[i].split()

# Create a list which includes all elements except the first one, combine the two lists using `zip`
words2 = words[1:]
myzip = zip(words,words2)

# Delete the tuples which start from "PERIOD" from the zipped list
mylist=[]
for i in myzip:
    if i[0]!='PERIOD':
        mylist.append(tuple(i))
        
print(mylist)

[('i', 'lived'), ('lived', 'there'), ('there', 'two'), ('two', 'years'), ('years', 'and'), ('and', 'two'), ('two', 'months'), ('months', 'PERIOD'), ('at', 'present'), ('present', 'i'), ('i', 'am'), ('am', 'a'), ('a', 'sojourner'), ('sojourner', 'in'), ('in', 'civilized'), ('civilized', 'life'), ('life', 'again'), ('again', 'PERIOD'), ('i', 'should'), ('should', 'not'), ('not', 'obtrude'), ('obtrude', 'my'), ('my', 'affairs'), ('affairs', 'so'), ('so', 'much'), ('much', 'on'), ('on', 'the'), ('the', 'notice'), ('notice', 'of'), ('of', 'my'), ('my', 'readers'), ('readers', 'if'), ('if', 'very'), ('very', 'particular'), ('particular', 'inquiries'), ('inquiries', 'had'), ('had', 'not'), ('not', 'been'), ('been', 'made'), ('made', 'by'), ('by', 'my'), ('my', 'townsmen'), ('townsmen', 'concerning'), ('concerning', 'my'), ('my', 'mode'), ('mode', 'of'), ('of', 'life'), ('life', 'which'), ('which', 'some'), ('some', 'would'), ('would', 'call'), ('call', 'impertinent'), ('impertinent', 'though'

#### 3. Count how often each pair of words occurs in the input text and record it for later retrieval.
 A. Use a dictionary of dictionaries  B. Use a numpy matrix

In [6]:
# Use numpy matrix: 
# Count the unique words in the inputfile
wordcount = len(set(words))
print(wordcount)

12857


In [7]:
# Generate a square matrix, equal in size to the number of unique words in the input file
import numpy as np

M = np.zeros(shape=(wordcount,wordcount))
uwords = list(set(words))
uwords.sort()

for element in mylist:
    i = uwords.index(element[0])
    j = uwords.index(element[1])
    M[i][j] += 1

In [8]:
# Display the first 5 lines of the frequency matrix
print(M[0:5])

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [9]:
# Count the frequency sum to check whether they are all zeros
sum = 0
for i in range(wordcount):
    for j in range(wordcount):
        sum += M[i][j]
print(sum)

117231.0


#### 4. Normalize the counts and turn them into probabilities.
For each word, find all paired words, add up their frequencies and divide each frequency by total. For example, if "i" is associated with "lived" and "am", and they both of occur once, their total occurrence is 2 and the resulting probabilities are "lived": 0.5, "am":0.5

In [10]:
# Convert to probabilities
for row in M:
    n = np.sum(row)
    if n > 0:
        row[:] = [f/n for f in row]

#### 5. Generate text based on this transition matrix
A. Pick a word at random (start with "the" if you like)
B. For the picked word, find all words it pairs with and get their probabilities. Pick the next word based on weighted probabilities. For example, if "the" is paired with "one" with probability .1 and "only" is paired with probability .3, "only" should be picked three times more likely than "one." Simplest way of doing this is via `random.choices()`.
C. Having picked a word, use logic from B to select the next word. Do this in a loop.
D. If "PERIOD" is picked, start a new sentence.
E. Generate one hundred sentences.

In [11]:
import random

sentences = []
for i in range(100):
    word1 = random.choices(uwords)[0] # Random starting word
    sentence = word1
    while word1 != 'PERIOD': # If "RERIOD" is picked, start a new sentence
        index = uwords.index(word1)
        prob_list = M[index]
        word2 = random.choices(uwords,weights=list(prob_list))[0]
        sentence += " " + word2
        word1 = word2
    sentences.append(sentence)

In [12]:
# Replace "PERIOD" by "." to make a sentence
for i in range(len(sentences)):
    sentences[i] = sentences[i].replace(" PERIOD",".")

# Generate 100 sentences
outputtext = sentences[0:100]
print(outputtext)

['motive for new satellites to know the pine spruce cedar—first second year and have also in the monsters in the ear will soon be tempted by his gnarled rind and she had been inspired directly or twelve inches long and as some way and that if we stood in the fewest obstacles to carry less in the middle leaving the divine in the interval of a september 1848.', 'blasted tree forty its own members and other wild ducks which is a general and women a forest which mode which grow by the previous state that we should thus a level on the bottomlessness of others savage places appeared to sensual savors when we should feel more rapidly yet.', 'sir kenelm digby thinks of loch fyne we have done and when she surveyed the third and anxiety as the town.', 'ample and echoed from both sides of the naturalist.', 'harshly for a hearth where.', '596-1887.', 'laboriosus_ was which is not yet pleasantly—large round before we are worth the bells the woodchoppers and each one afternoon after a village.', 're

In [13]:
file = open('output.txt','w')
for sentence in outputtext:
    file.write(sentence + '\n')
file.close()